### ISSUE TITLE
Problem-Test People Search

### ISSUE THREAD

**Issue by greymalkin3** [drdavidknott/betterstart#106]
Getting some very funky results on searches between the different projects.

For example TTTs - everyone is duplicated on the search results but there is only one record when you click through; on ABSS there are no deliverers, on ABSS Copy, searches for deliverers results in beneficiaries.

If you want me to narrow this down further, I need some guidance as to what information would help you.

**Comment by drdavidknott** [comment]
Fixed - please test.

**Comment by greymalkin3** [comment]
Thank you
