### ISSUE TITLE
Problem - Activities not showing correctly (Feb 22)

### ISSUE THREAD

**Issue by greymalkin3** [drdavidknott/betterstart#112]
If you look at a person, for example Taiwo, they have no activities listed. If you do a download, they have 49 activities.

If I add a new activity, then it will appear on the screen, for example Kye.

It appears that there is a cut off: any activities before September 2021 do not appear on the screen, but do appear in the download.

I have tried reloading activities, but this did not work

**Comment by greymalkin3** [comment]
This was first identified in issue 77 which has now been closed as it duplicated this issue

**Comment by drdavidknott** [comment]
Needed to run admin job - now run.
