### ISSUE TITLE
PROBLEM: People Start Date is not appearing in download

### ISSUE THREAD

**Issue by greymalkin3** [drdavidknott/betterstart#114]
People have joined the project since 1/1/22 but when I do a download and search for them, the start date field is empty on the download. Their correct start date is shown on the screen.

This does not affect everyone. I still have start dates for people who joined before 2022 although I don't know if these are complete.

**Comment by drdavidknott** [comment]
Bug found and fixed - please confirm retest.

**Comment by drdavidknott** [comment]
Confirmed working.
