### ISSUE TITLE
Urgent Development - The ability to change event types

### ISSUE THREAD

**Issue by greymalkin3** [drdavidknott/betterstart#115]
Please can I have the ability to bulk change event types?

The situation is that ABSS have changed our reporting requirements. Unfortunately there is not a straight map from the existing event types to the new ones so I cannot just re-name them.

This is the problem
[Book2.xlsx](https://github.com/drdavidknott/betterstart/files/8514167/Book2.xlsx)

The ideal solution for me would be if I can download all the events - modify them to match the new event types and then reload them. very similar as to how the postcode change worked.

Thank you

**Comment by drdavidknott** [comment]
Change made and tested.
