### ISSUE TITLE
New Trained Role Type

### ISSUE THREAD

**Issue by greymalkin3** [drdavidknott/betterstart#116]
I am trying to set up a new trained role type (Rising 4). I expected it to appear on the person data entry screen as attached.
What have I done wrong?

![image](https://user-images.githubusercontent.com/52622525/180762124-0d55782b-9841-4b50-ba6c-195220117c43.png)

**Comment by drdavidknott** [comment]
Roles also need to be connected to valid age statuses before they appear for people with that age status: looks like that hasn't been done.
