### ISSUE TITLE
Development Idea - Venues

### ISSUE THREAD

**Issue by greymalkin3** [drdavidknott/betterstart#23]
The ability to store information about the venues we use for events or places we may use

This includes name of venue, type of venue (cafe, children's centre, etc), address, phone, email, website, ward, prices, contact information, opening hours, notes.

Not all these fields will be mandatory but I think these should be: venue, type of venue (cafe, children's centre, etc), address

I think I would prefer we make the name of venue unique

**Comment by drdavidknott** [comment]
New venue capability added.
