### ISSUE TITLE
Development/Reporting - Identifying groups of carers by the age of their children

### ISSUE THREAD

**Issue by greymalkin3** [drdavidknott/betterstart#46]
This is a complicated one and I'm not quite sure of how to do it (or even to explain it).

We often need to target things to parents by the age of their child. For example anything to do with breastfeeding should usually be targeted to under 1s, whereas preparation for nursery school is usually 3 and up.

What we need is to be able to select a group of parents based on their child's age in years (0-1, 1-2, 2-3, 3-4)

Can you come up with a cunning plan?

**Comment by drdavidknott** [comment]
Age range term added to person search.
