### ISSUE TITLE
Problem - I can't look at the details for Tracey Knott

### ISSUE THREAD

**Issue by greymalkin3** [drdavidknott/betterstart#79]
Request Method: | GET
-- | --
https://betterstart-uat.appspot.com/person/1
3.0.7
MultipleObjectsReturned
get() returned more than one Answer -- it returned 2!
/layers/google.python.pip/pip/lib/python3.7/site-packages/django/db/models/query.py in get, line 422
/layers/google.python.pip/pip/bin/python3
3.7.10
['/srv',  '/workspace',  '/layers/google.python.pip/pip/bin',  '/opt/python3.7/lib/python37.zip',  '/opt/python3.7/lib/python3.7',  '/opt/python3.7/lib/python3.7/lib-dynload',  '/layers/google.python.pip/pip/lib/python3.7/site-packages',  '/opt/python3.7/lib/python3.7/site-packages']
Thu, 4 Mar 2021 17:46:20 +0000

**Comment by drdavidknott** [comment]
Fixed - reference data error
